# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Install appwrite
    init: |
      npm i -g appwrite-cli
      cd $GITPOD_REPO_ROOT/appwrite
      docker-compose pull
    command: |
      cd $GITPOD_REPO_ROOT/appwrite
      docker-compose up -d
      gp sync-done appwrite
  - name: Prepare appwrite database - load backup and add gitpod url to origin
    command: |
      gp sync-await appwrite
      cd $GITPOD_REPO_ROOT/appwrite
      sleep 3
      sudo sh -c "docker-compose exec -T mariadb sh -c 'exec mysql -uroot -p"rootsecretpassword"' < dump.sql"
      sudo -E bash $GITPOD_REPO_ROOT/.gitpod/addOrigin.sh
  - init: |
      cp .env.example .env.local
      npm install
    command: |
      gp sync-await appwrite
      sudo -E bash $GITPOD_REPO_ROOT/.gitpod/updateEndpointUrl.sh
      npm run dev

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-browser
  - port: 8080
    visibility: public
