# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Install appwrite
    init: |
      npm i -g appwrite-cli
      cd $GITPOD_REPO_ROOT/appwrite
      docker-compose pull
    command: |
      cd $GITPOD_REPO_ROOT/appwrite
      docker-compose up -d
      gp sync-done appwrite
  - name: Prepare appwrite database - load backup and add gitpod web app
    command: |
      gp sync-await appwrite
      sleep 3
      npm run loadDB
      npm run gitpod:addOrigin
  - name: Appwrite functions
    init: |
      cd $GITPOD_REPO_ROOT/functions/FetchFromHackernews
      npm i
  - name: Install appwrite-cli
    init: npm i -g appwrite-cli@0.15
  - name: NextJS
    init: |
      cp .env.example .env.local
      npm install
    command: |
      gp sync-await appwrite
      npm run gitpod:updateEndpointUrl
      npm run dev

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-browser
  - port: 8080
    visibility: public
