import {
  Button,
  Checkbox,
  Col,
  Container,
  Input,
  Row,
  Spacer,
  styled,
  Switch,
  Text,
} from "@nextui-org/react";
import { Models } from "appwrite";
import { motion } from "framer-motion";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import api from "../api";
import config from "../config";
import useCollectionList from "../hooks/useCollection";
import { Todo } from "../models/todo";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [todos, setTodos] = useCollectionList<Todo>({ collectionId: config.COLLECTION_ID });
  const [input, setInput] = useState("");

  const createTodo = () => {
    api
      .provider()
      .database.createDocument<Todo>(config.COLLECTION_ID, "unique()", {
        content: input,
        createdAt: Date.now(),
      });
  };

  const updateTodo = async (id: string, isDone: boolean) => {
    await api
      .provider()
      .database.updateDocument(config.COLLECTION_ID, id, { isDone });
  };

  const deleteTodo = async (id: string) => {
    await api.provider().database.deleteDocument(config.COLLECTION_ID, id);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Row justify="center" align="center">
          <div>
            <h1>Todo list!</h1>
            <div style={{ marginBottom: "1rem" }}>
              <form onSubmit={(e) => { e.preventDefault(); createTodo(); setInput(""); }}>
                <Input
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  shadow={false}
                  type="text"
                  placeholder="What you have to do?"
                  aria-label="content"
                  contentRight={
                    <>
                      <Spacer x={2} />
                      <Button
                        style={{ minWidth: "3rem" }}
                      >
                        +
                      </Button>
                    </>
                  }
                />
              </form>
            </div>
            <Container
              style={{
                display: "flex",
                gap: "0.3rem",
                flexDirection: "column",
              }}
            >
              {todos?.documents
                .sort((a, b) => {
                  if (a.isDone === b.isDone) {
                    return b.createdAt - a.createdAt;
                  }
                  return a.isDone ? 1 : -1;
                })
                .map((document) => (
                  <motion.div layout key={document.$id}>
                    <Row justify="space-between" align="center">
                      <Col>
                        <Text>{document.content}</Text>
                      </Col>
                      <Col>
                        <Row align="center">
                          <Checkbox
                            checked={document.isDone}
                            onChange={(e) => {
                              updateTodo(document.$id, e);
                            }}
                          />
                          <Spacer x={1} />
                          <Button color="error" style={{ minWidth: "1rem" }} onClick={() => deleteTodo(document.$id)}>X</Button>
                        </Row>
                      </Col>
                    </Row>
                  </motion.div>
                ))}
            </Container>
          </div>
        </Row>
      </Container>
    </div>
  );
};

export default Home;
